#include<iostream.h>
#include<conio.h>
main()
{
clrscr();
int a,b,c,d,e,f,g,h,i,j,k;
		cout<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<"                    1 for Telephone          2 for Electricity"<<endl<<" "<<endl<<"                    3 for Gas                4 for Card or Loan payment"<<endl<<" "<<endl<<"                    5 for Main Manu"<<endl;
		cin>>a;
		clrscr();
					{
					switch(a)
							  {
								 case 1:
								 {
								 cout<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<"                     1 for Warid                2 for Telenor"<<endl<<" "<<endl<<"                     3 for Ufone                4 for Jazz"<<endl<<endl<<"                     5 for Zong                 6 for PTCL"<<endl<<endl<<"                     7 for Main Manu"<<endl;
								 cin>>b;
								 clrscr();
											 {
											 switch(b)
														{
														 {
														 case 7:
														 cout<<"goto main";
														 break;
														 }
														}
											  }
								clrscr();
								cout<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<"                        Please select your account service"<<endl<<endl<<"                     1 for Post-Paid               2 for Pre-Paid"<<endl<<endl<<"                     3 for Main manu"<<endl;
								cin>>c;
											 {
											 switch(c)
														{
															{
							                     	case 3:
															cout<<"goto main";
															break;
															}
														}
											}
								break;
								}



								case 2:
								{
								cout<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<"                    Please select the electricity supplier company."<<endl<<endl<<"                    1 for LESCO               2 for KESC"<<endl<<endl<<"                    3 for Main manu"<<endl;
								cin>>d;
										 {
										 switch(d)
													{
														{
														case 3:
														cout<<"goto main";
														break;
														}
													}
										 }
								clrscr();
								cout<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<"                       Please enter the '13' digit account number."<<endl<<endl<<endl<<endl<<endl<<"                      1 for Main manu"<<endl;
								cin>>e;
										{
										switch(e)
												  {
													  {
													  case 1:
													  cout<<"goto main";
													  break;
													  }
												  }
										}
								break;
								}


								case 3:
								{
								cout<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<"                    Please select the gas supplier company."<<endl<<endl<<"                    1 for SSGC                 2 for SNGPL"<<endl<<endl<<"                    3 for Main manu"<<endl;
								cin>>f;
										{
										switch(f)
												  {
													  {
													  case 3:
													  cout<<"goto main";
													  break;
													  }
												  }
										 }
								 clrscr();
								 cout<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<"                    Please insert/enter the '10' digit customer no."<<endl<<endl<<endl<<endl<<endl<<"                    1 for Main manu"<<endl;
								 cin>>g;
										 {
										 switch(g)
													{
														{
														case 1:
														cout<<"goto main";
														break;
														}
													}
										  }
								  break;
								  }

								  case 4:
								  {
								  cout<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<"                   Card or Loan payment"<<endl;
								  getch();
								  clrscr();
								  cout<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<"                   Cradit Card "<<endl;
								  getch();
								  clrscr();
								  cout<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<endl<<"                   Customer account number"<<endl<<endl<<endl<<endl<<endl<<"                   1 for Main manu"<<endl;
								  cin>>h;
										  {
										  switch(h)
													 {
														  {
														  case 1:
														  cout<<"goto main";
														  break;
														  }
													 }
										  }
								  break;
								  }
								}
				  }
getch();
}





