#include<iostream.h>
#include<conio.h>
main()
{
clrscr();
cout<<" Number | Square |  Cube |"<<endl;
cout<<"--------------------------"<<endl;
cout<<"   1    |   1    |  1    |"<<endl;
cout<<"   2    |   4    |  8    |"<<endl;
cout<<"   3    |   9    |  27   |"<<endl;
cout<<"   4    |   16   |  64   |"<<endl;
cout<<"   5    |   25   |  125  |"<<endl;
cout<<"   6    |   36   |  216  |"<<endl;
cout<<"   7    |   49   |  343  |"<<endl;
cout<<"   8    |   64   |  512  |"<<endl;
cout<<"   9    |   81   |  729  |"<<endl;
cout<<"   10   |   100  |  100  |"<<endl;
getch();
}



